version: "3.8"
services:
  client:
    build: client
    stdin_open: true
    container_name: client
    image: todo_client
    restart: always
    depends_on:
      - server
    ports:
      - 80:80
    networks:
      - react-express

  server:
    container_name: server
    restart: always
    build: server
    depends_on:
      - mongo
    ports:
      - 8080:8080
    networks:
      - express-mongo
      - react-express
    image: todo_server

  mongo:
    container_name: mongo
    restart: always
    build: mongo
    ports:
      - 27017:27017
    networks:
      - express-mongo
    image: todo_mongo

networks:
  react-express:
  express-mongo:
