apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-client
  labels:
    name: deploy-client
    app: deploy-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deploy-client
      app: deploy-client
  template:
    metadata:
      name: deploy-client
      labels:
        name: deploy-client
        app: deploy-client
    spec:
      containers:
        - name: deploy-client
          image: "sukruciris/mern_client:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
