apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    name: testing-kube-deploy
    app: testing-kube-app
spec:
  type: LoadBalancer
  selector:
    app: testing-kube-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
