apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deploy-mongo
  labels:
    name: testing-kube-deploy
    app: testing-kube-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: testing-kube-pod
      app: testing-kube-app
  template:
    metadata:
      name: testing-kube-pod
      labels:
        name: testing-kube-pod
        app: testing-kube-app
    spec:
      containers:
        - name: testing-kube-container
          image: "sukruciris/mern_mongo:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
  volumes:
    - name: "mongo-persistent-storage"
      persistentVolumeClaim:
        claimName: "mongo-persistent-storage"
