apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: testing-kube-deploy
    app: testing-kube-app
spec:
  type: ClusterIP
  selector:
    app: testing-kube-app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
