apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    name: server
    app: todo-app
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
