apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-server
  labels:
    name: testing-kube-deploy
    app: testing-kube-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: testing-kube-pod
      app: testing-kube-app
  template:
    metadata:
      name: testing-kube-pod
      labels:
        name: testing-kube-pod
        app: testing-kube-app
    spec:
      containers:
        - name: testing-kube-container
          image: "sukruciris/mern_server:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      volumes:
        - name: todo-volume
          gcePersistentDisk:
            pdName: todo-disk
            fsType: ext4
