name: Docker Image CI-CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker compose build
      - run: docker compose push
      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - run: gcloud container clusters get-credentials todo-cluster --zone europe-west1-b
      - run: cd kubernetes-configs
      - run: sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
      - run: kubectl apply -f .
