name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  runMultipleCommands:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker compose build
    - run: docker compose push
